kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.main.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.global.registry }}/{{ .Values.main.image }}:{{ .Values.main.tag }}"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "{{ .Values.main.env.springProfile }}"
            - name: SPRING_MAIN_BANNER-MODE
              value: "off"
            - name: TZ
              value: Europe/Moscow
            - name: JAVA_TOOL_OPTIONS
              value: "-Dfile.encoding=UTF-8 -Duser.language=ru -Duser.country=RU -Dspring.config.location=file:/opt/app/application-{{ .Values.main.env.springProfile }}.yaml"
          volumeMounts:
            - name: {{ .Release.Name }}-application-config
              mountPath: /opt/app/application-{{ .Values.main.env.springProfile }}.yaml
              subPath: application-{{ .Values.main.env.springProfile }}.yaml
          ports:
            - containerPort: {{ .Values.main.port }}
              protocol: TCP
          resources: {{ toYaml .Values.main.resources | nindent 12 }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: {{ .Values.main.pullPolicy }}
{{- if ne .Values.global.stand "prod" }}
  strategy:
    type: Recreate
{{- end }}
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600