apiVersion: v1
kind: Secret
metadata:
  name: { { .Release.Name } }-application-config
  namespace: { { .Values.global.namespace } }
  labels:
    app: { { .Release.Name } }
type: Opaque
data:
  application-{{ .Values.main.env.springProfile }}.yaml: |-
    {{- $path := printf "config/application-%s.yaml" .Values.main.env.springProfile }}
    {{ (tpl (.Files.Get $path) . ) | b64enc | indent 2 }}