spring:
  liquibase:
    change-log: classpath:db/changelog-master.xml
  application:
    name: rest-proxy-stub
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: ${SHOW_SQL:false}
server:
  port: ${APP_PORT}
  error:
    include-message: always

logging:
  level:
    ru.vtb.stub: ${LOGGING_LEVEL}
    org.springframework.web: DEBUG
    root: DEBUG
    feign.Logger: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO

path:
  data: /stub/data
  response: /stub/response

ribbon:
  eureka:
    enabled: false

team:
  codes:
    - team1
    - team2

rest-proxy-stub:
  storage-mode: ${STORAGE_MODE}

zuul:
  routes:
    session:
      url: ${ZUUL_ROUTES_SESSION_URL}
      path: ${ZUUL_ROUTES_SESSION_PATH}
    session-onb:
      url: ${ZUUL_ROUTES_SESSION_ONB_URL}
      path: ${ZUUL_ROUTES_SESSION_ONB_PATH}
    card-ul:
      url: ${ZUUL_ROUTES_CARD_UL_URL}
      path: ${ZUUL_ROUTES_CARD_UL_PATH}
    card-fl:
      url: ${ZUUL_ROUTES_CARD_FL_URL}
      path: ${ZUUL_ROUTES_CARD_FL_PATH}
    egr:
      url: ${ZUUL_ROUTES_EGR_URL}
      path: ${ZUUL_ROUTES_EGR_PATH}

prefix:
  teams:
    - onb1
    - onb2
    - onb3_st
    - onb3_dev
    - onb3_front
    - onb4
    - onb5
    - kpk
    - mobile
    - accr
    - onb7_st
    - onb7_dev
    - onb7_front
    - etalon-sync
    - credential
    - accr-open-dev
    - cole-company-info