spring:
  application:
    name: rest-proxy-stub

server:
  port: 8888
  error:
    include-message: always

logging:
  level:
    ru.vtb.stub: DEBUG
    org.springframework.web: INFO

path:
  data: /stub/data
  response: /stub/response

db:
  platform: postgresql
  url: jdbc:postgresql://localhost:5432/rest_proxy_stub
  user: rest_proxy
  password: 123

zuul:
  routes:
    session:
      url: http://session-stub-stubs-ds1-genr01-onbc-onb-development.apps.ds1-genr01.corp.dev.vtb/session
      path: /session/**
    session-onb:
      url: http://session-stub-stubs-ds1-genr01-onbc-onb-development.apps.ds1-genr01.corp.dev.vtb/onb/session
      path: /onb/session/**
    card-ul:
      url: http://card-ul-stub-stubs-ds1-genr01-onbc-onb-development.apps.ds1-genr01.corp.dev.vtb/onb/api/v1/etalons/get
      path: /onb/api/v1/etalons/get/**
    card-fl:
      url: http://card-fl-stub-stubs-ds1-genr01-onbc-onb-development.apps.ds1-genr01.corp.dev.vtb/person/get
      path: /person/get/**
    egr:
      url: http://stubs-dso-smeonboard.apps.d0-oscp.corp.dev.vtb/cbext/fns/egr/info
      path: /cbext/fns/egr/info/**

ribbon:
  eureka:
    enabled: false

team:
  codes:
    - team1
    - team2