spring:
  application:
    name: rest-proxy-stub

server:
  port: ${APP_PORT}
  error:
    include-message: always

logging:
  level:
    ru.vtb.stub: ${LOGGING_LEVEL}
    org.springframework.web: INFO

path:
  data: /stub/data
  response: /stub/response

ribbon:
  eureka:
    enabled: false

zuul:
  routes:
    session:
      url: ${ZUUL_ROUTES_SESSION_URL}
      path: ${ZUUL_ROUTES_SESSION_PATH}
    session-onb:
      url: ${ZUUL_ROUTES_SESSION_ONB_URL}
      path: ${ZUUL_ROUTES_SESSION_ONB_PATH}
    card-ul:
      url: ${ZUUL_ROUTES_CARD_UL_URL}
      path: ${ZUUL_ROUTES_CARD_UL_PATH}
    card-fl:
      url: ${ZUUL_ROUTES_CARD_FL_URL}
      path: ${ZUUL_ROUTES_CARD_FL_PATH}
    egr:
      url: ${ZUUL_ROUTES_EGR_URL}
      path: ${ZUUL_ROUTES_EGR_PATH}
generate:
  fields:
    - name: requestId
      type: uuid
    - name: mdmCode
      type: long
      min: 1000000000
      max: 9999999999
    - name: mdmCode2
      type: longAsString
      min: 1000000000
      max: 9999999999

prefix:
  teams:
    - onb1
    - onb2
    - onb3_st
    - onb3_dev
    - onb3_front
    - onb4
    - onb5
    - kpk
    - mobile
    - accr
    - onb7_st
    - onb7_dev
    - onb7_front
    - etalon-sync
    - credential
    - accr-open-dev
    - cole-company-info