spring:
  liquibase:
    change-log: classpath:db/changelog-master.xml
  application:
    name: rest-proxy-stub
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: ${SHOW_SQL:false}
server:
  port: 8888
  error:
    include-message: always

logging:
  level:
    ru:
      vtb: DEBUG
    root: DEBUG
    feign.Logger: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO

path:
  data: /stub/data
  response: /stub/response

zuul:
  routes:
    session:
      url: http://session-stub-stubs-ds1-genr01-onbc-onb-development.apps.ds1-genr01.corp.dev.vtb/session
      path: /session/**
    session-onb:
      url: http://session-stub-stubs-ds1-genr01-onbc-onb-development.apps.ds1-genr01.corp.dev.vtb/onb/session
      path: /onb/session/**
    card-ul:
      url: http://card-ul-stub-stubs-ds1-genr01-onbc-onb-development.apps.ds1-genr01.corp.dev.vtb/onb/api/v1/etalons/get
      path: /onb/api/v1/etalons/get/**
    card-fl:
      url: http://card-fl-stub-stubs-ds1-genr01-onbc-onb-development.apps.ds1-genr01.corp.dev.vtb/person/get
      path: /person/get/**
    egr:
      url: http://stubs-dso-smeonboard.apps.d0-oscp.corp.dev.vtb/cbext/fns/egr/info
      path: /cbext/fns/egr/info/**

ribbon:
  eureka:
    enabled: false

team:
  codes:
    - team1
    - team2

rest-proxy-stub:
  storage-mode: ${STORAGE_MODE}
