global:
  # Openshift namespace в который производится деплой
  namespace: ds1-genr01-onbc-onb-development
  # Репозиторий из которого загружаются образы
  registry: nexus-ci.corp.dev.vtb/onb-docker-snapshot
  # Код проекта для мониторинга
  projectCode: SMEO
  # Стенд, используется для создания секретов с нужными сертификатами для конкретного стенда
  stand: dev

route:
  enabled: false
  host:

  # Параметры проб для main
  Probe:
    port: 8080
    enabled: true
    livenessProbe:
      path: "/actuator/health/liveness"
      failureThreshold: 10
      initialDelaySeconds: 60
      periodSeconds: 15
    readinessProbe:
      path: "/actuator/health/readiness"
      failureThreshold: 10
      initialDelaySeconds: 90
      periodSeconds: 10

# Настройки основного приложения
main:
  # Количество реплик подов
  replicaCount: 1
  # Образ в репозитории
  image: stubs/rest-proxy-stub
  # Тег образа
  tag: ""
  # Политика кеширования образов на нодах
  pullPolicy: Always
  # Порт, на котором принимает запросы приложение
  port: 8080
  # Параметры переменных окружения в поде
  env:
    # Профиль, используемый Spring Boot
    springProfile: dev
  # Ресурсы, выделяемые на под
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
    limits:
      cpu: 100m
      memory: 200Mi