global:
  # Openshift namespace в который производится деплой
  namespace: ss1-genr01-onbc-onb-ift
  # Репозиторий из которого загружаются образы
  registry: nexus-cd.region.vtb.ru/onb-docker-test-g
  # Код проекта для мониторига
  projectCode: SMEO
  # Стенд, используется для создания секретов с нужными сертификатами для конкретного стенда
  stand: ift

route:
  enabled: true
  host:

# Настройки основного приложения
main:
  # Количество реплик подов
  replicaCount: 1
  # Образ в репозитории
  image: stubs/rest-proxy-stub
  # Тег образа
  tag: ""
  env:
    # Профиль, используемый Spring Boot
    springProfile: ift
  resources:
    requests:
      cpu: 100m
      memory: 300Mi
    limits:
      cpu: 100m
      memory: 300Mi