global:
  # Openshift namespace в который производится деплой
  namespace: ds1-genr01-onbc-onb-development
  # Репозиторий из которого загружаются образы
  registry: nexus-ci.corp.dev.vtb/onb-docker-snapshot
  # Код проекта для мониторига
  projectCode: SMEO
  # Стенд, используется для создания секретов с нужными сертификатами для конкретного стенда
  stand: dev

route:
  enabled: true
  host:

# Настройки основного приложения
main:
  # Количество реплик подов
  replicaCount: 1
  # Образ в репозитории
  image: stubs/rest-proxy-stub
  # Тег образа
  tag: ""
  env:
    # Профиль, используемый Spring Boot
    springProfile: dev
  resources:
    requests:
      cpu: 100m
      memory: 300Mi
    limits:
      cpu: 300m
      memory: 300Mi